
# travis-ci.com
language: julia
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  ## Create Documentation 
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia -e 'using Pkg;
              Pkg.activate(".");
              Pkg.instantiate();'
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

script:
  - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test("MinimalRLCore", coverage=true)'
